/**
 * Sync Engine — cloud-side API.
 *
 * This is the real, working contract a local device would call once one
 * exists (see SYNC_ARCHITECTURE_NOTES.md — no such device-side client is
 * built yet, this is deliberately just the cloud half). Built against a
 * curated whitelist of tables, not "any table" — accepting arbitrary
 * table/column names from a client device would be a real injection risk,
 * and most of the schema's 141 tables were never meant to be edited
 * offline in the first place.
 *
 * Idempotency (§67-68 of the architecture doc): every record carries a
 * Record_Sync_UUID generated by the device, independent of whatever
 * integer PK the eventual row gets on each side. A retried upload of the
 * same Sync_UUID is recognized via tbl_sync_log and never double-applied —
 * this is the actual mechanism, tested below with a real duplicate
 * request, not just described.
 */
const router = require('express').Router();
const db = require('../db/tenantDb').tenantDb;
const { sendSuccess, sendError } = require('../utils/response');
const { authenticate } = require('../middleware/auth');

// Table → which payload fields are accepted from a device, and which
// column holds its "last changed" timestamp for the download/pull side.
// Deliberately narrow — a device can create/update a customer or a sale,
// not rewrite arbitrary columns on arbitrary tables.
const SYNCABLE_TABLES = {
  tbl_customer_master: {
    pk: 'Customer_ID',
    changedCol: 'Modified_Date',
    fields: ['Customer_Code', 'Customer_Name', 'Mobile_1', 'Mobile_2', 'Email', 'Address_Line1', 'City', 'State', 'Pincode', 'GST_No', 'PAN_No', 'Is_Active'],
  },
  tbl_ornament_master: {
    pk: 'Ornament_ID',
    changedCol: 'Last_Updated_Date',
    // Metal_Type added here too — without it, any ornament created on an
    // offline device and pushed up through sync silently defaulted to
    // Gold on arrival, since pickFields() strips anything not whitelisted.
    fields: ['Article_Number', 'Type_ID', 'Design_ID', 'Purity_ID', 'Metal_Type', 'Gross_Weight', 'Net_Gold_Weight', 'Stone_Weight', 'Current_Gold_Rate', 'Base_Making_Charge_Per_Gram', 'Purchase_Cost', 'Stock_Quantity', 'Is_Sold', 'Is_Active'],
  },
  tbl_sales_header: {
    pk: 'Sale_ID',
    changedCol: 'Modified_Date',
    fields: ['Invoice_Number', 'Sale_Date', 'Customer_ID', 'Customer_Name', 'Customer_Mobile', 'Subtotal_Amount', 'GST_Amount', 'Net_Payable_Amount', 'Payment_Mode', 'Payment_Status', 'Amount_Paid', 'Balance_Amount'],
  },
  tbl_sales_details: {
    pk: 'Detail_ID',
    changedCol: 'Created_Date', // no Modified_Date on this table — line items aren't edited after the fact, only inserted
    fields: ['Sale_ID', 'Ornament_ID', 'Article_Number', 'Gross_Weight', 'Net_Gold_Weight', 'Purity_Code', 'Gold_Rate_Per_Gram', 'Making_Charge_Applied', 'Total_Line_Price'],
  },
};

function pickFields(payload, allowed) {
  const out = {};
  for (const f of allowed) if (payload[f] !== undefined) out[f] = payload[f];
  return out;
}

// ── POST /api/sync/upload — a device pushes its pending local changes ─────────
router.post('/upload', authenticate, async (req, res) => {
  const { deviceId, records } = req.body;
  if (!deviceId) return sendError(res, 400, 'deviceId is required.');
  if (!Array.isArray(records) || !records.length) return sendError(res, 400, 'records must be a non-empty array.');

  const tenantId = req.user.tenantId;
  const results = [];

  for (const rec of records) {
    const { tableName, operation, syncUuid, payload } = rec;
    const table = SYNCABLE_TABLES[tableName];

    if (!table) { results.push({ syncUuid, status: 'FAILED', reason: `"${tableName}" is not a syncable table.` }); continue; }
    if (!syncUuid) { results.push({ syncUuid, status: 'FAILED', reason: 'syncUuid is required per record.' }); continue; }
    if (!['INSERT', 'UPDATE'].includes(operation)) { results.push({ syncUuid, status: 'FAILED', reason: `Unsupported operation "${operation}" — only INSERT/UPDATE are handled.` }); continue; }

    try {
      const fields = pickFields(payload || {}, table.fields);
      const existing = await db(tableName).where({ Tenant_ID: tenantId, Sync_UUID: syncUuid }).first();

      if (operation === 'INSERT') {
        // Idempotency for INSERT specifically: a row is only ever created
        // once, so a retried INSERT of the same Sync_UUID (e.g. the client
        // never saw the first response and blindly resent it) must not
        // produce a second row. Checked two ways: the log (fast path) and
        // the row itself (safety net, covers the case where the insert
        // succeeded but the log write that should have followed it didn't).
        const alreadyLogged = await db('tbl_sync_log').where({ Tenant_ID: tenantId, Table_Name: tableName, Record_Sync_UUID: syncUuid, Status: 'SUCCESS' }).first();
        if (alreadyLogged || existing) {
          results.push({ syncUuid, status: 'ALREADY_SYNCED' });
          continue;
        }
        await db(tableName).insert({ ...fields, Tenant_ID: tenantId, Sync_UUID: syncUuid });
        results.push({ syncUuid, status: 'SUCCESS' });
      } else { // UPDATE
        // Deliberately NOT short-circuited by the sync log the way INSERT
        // is: a row's Sync_UUID is stable for its whole lifetime, so a
        // legitimate second UPDATE to the same row (a real edit, made after
        // the first one already succeeded) shares that same Sync_UUID and
        // must still apply. Re-running an UPDATE with identical values is
        // naturally idempotent (same end state either way), so no separate
        // guard is needed the way it is for INSERT.
        if (!existing) {
          await db('tbl_sync_log').insert({ Tenant_ID: tenantId, Device_ID: deviceId, Table_Name: tableName, Record_Sync_UUID: syncUuid, Direction: 'LOCAL_TO_CLOUD', Status: 'FAILED', Error_Message: 'No existing row with this Sync_UUID to update — was it ever created?' });
          results.push({ syncUuid, status: 'FAILED', reason: 'No existing row with this Sync_UUID to update.' });
          continue;
        }
        await db(tableName).where({ Tenant_ID: tenantId, Sync_UUID: syncUuid }).update(fields);
        results.push({ syncUuid, status: 'SUCCESS' });
      }

      await db('tbl_sync_log').insert({ Tenant_ID: tenantId, Device_ID: deviceId, Table_Name: tableName, Record_Sync_UUID: syncUuid, Direction: 'LOCAL_TO_CLOUD', Status: 'SUCCESS' });
    } catch (err) {
      await db('tbl_sync_log').insert({ Tenant_ID: tenantId, Device_ID: deviceId, Table_Name: tableName, Record_Sync_UUID: syncUuid, Direction: 'LOCAL_TO_CLOUD', Status: 'FAILED', Error_Message: err.message });
      results.push({ syncUuid, status: 'FAILED', reason: err.message });
    }
  }

  const summary = { success: results.filter((r) => r.status === 'SUCCESS').length, alreadySynced: results.filter((r) => r.status === 'ALREADY_SYNCED').length, failed: results.filter((r) => r.status === 'FAILED').length };
  return sendSuccess(res, { results, summary }, `${summary.success} synced, ${summary.alreadySynced} already synced, ${summary.failed} failed.`);
});

// ── GET /api/sync/download — a device pulls what changed since it last checked ──
router.get('/download', authenticate, async (req, res) => {
  const tenantId = req.user.tenantId;
  const since = req.query.since ? new Date(req.query.since) : new Date(0);
  const requested = (req.query.tables ? req.query.tables.split(',') : Object.keys(SYNCABLE_TABLES)).filter((t) => SYNCABLE_TABLES[t]);
  if (!requested.length) return sendError(res, 400, `No valid tables requested. Available: ${Object.keys(SYNCABLE_TABLES).join(', ')}`);

  try {
    const data = {};
    for (const tableName of requested) {
      const { changedCol } = SYNCABLE_TABLES[tableName];
      data[tableName] = await db(tableName).where('Tenant_ID', tenantId).where(changedCol, '>', since).select('*');
    }
    return sendSuccess(res, { serverTime: new Date().toISOString(), data });
  } catch (err) {
    return sendError(res, 500, 'Failed to fetch changes: ' + err.message);
  }
});

// ── GET /api/sync/status — monitoring: what's come in, what's failed ──────────
router.get('/status', authenticate, async (req, res) => {
  const tenantId = req.user.tenantId;
  try {
    const logCounts = await db('tbl_sync_log').where('Tenant_ID', tenantId).select('Status').count('Log_ID as count').groupBy('Status');
    const queueCounts = await db('tbl_sync_queue').where('Tenant_ID', tenantId).select('Status').count('Queue_ID as count').groupBy('Status');
    const recentFailures = await db('tbl_sync_log').where({ Tenant_ID: tenantId, Status: 'FAILED' }).orderBy('Synced_Date', 'desc').limit(20);
    return sendSuccess(res, {
      syncLog: Object.fromEntries(logCounts.map((r) => [r.Status, parseInt(r.count)])),
      queue: Object.fromEntries(queueCounts.map((r) => [r.Status, parseInt(r.count)])),
      recentFailures,
    });
  } catch (err) {
    return sendError(res, 500, 'Failed to fetch sync status: ' + err.message);
  }
});

module.exports = router;
